container_image = docker://hyan84/centos7
universe = container

log = exp10/NWE$(Cluster).log
transfer_input_files = exp10.py, generator.py, utils.py, lowRank.py, params10.txt
arguments = $(n) $(mu) $(mu_rate)
executable = exp10.sh

output = exp10/NWE$(Cluster)_$(Process).out
error = exp10/NWE$(Cluster)_$(Process).err 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 1
request_memory = 40GB
request_disk = 2GB 

queue 1 n, mu, mu_rate from params10.txt