container_image = docker://hyan84/centos7
universe = container

log = exp1/NWE$(Cluster).log
transfer_input_files = exp1.py, generator.py, utils.py, sdp.py, lowRank.py, glasso.py, params1.txt
arguments = $(n) $(mu) $(rate)
executable = exp1.sh

output = exp1/NWE$(Cluster)_$(Process).out
error = exp1/NWE$(Cluster)_$(Process).err 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 1
request_memory = 20GB
request_disk = 2GB 

queue 30 n, mu, rate from params1.txt