container_image = docker://hyan84/centos7
universe = container

log = exp2/NWE$(Cluster).log
transfer_input_files = exp2.py, generator.py, utils.py, sdp.py, lowRank.py, glasso.py, params2.txt
arguments = $(n)
executable = exp2.sh

output = exp2/NWE$(Cluster)_$(Process).out
error = exp2/NWE$(Cluster)_$(Process).err 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 1
request_memory = 20GB
request_disk = 2GB 

queue 30 n from params2.txt