container_image = docker://hyan84/centos7
universe = container

log = exp3/NWE$(Cluster).log
transfer_input_files = exp3.py, generator.py, utils.py, sdp.py, lowRank.py, glasso.py, params3.txt
arguments = $(n)
executable = exp3.sh

output = exp3/NWE$(Cluster)_$(Process).out
error = exp3/NWE$(Cluster)_$(Process).err 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 1
request_memory = 20GB
request_disk = 2GB 

queue 30 n from params3.txt