container_image = docker://hyan84/centos7
universe = container

log = exp4/NWE$(Cluster).log
transfer_input_files = exp4.py, generator.py, utils.py, sdp.py, lowRank.py, glasso.py, params4.txt
arguments = $(n)
executable = exp4.sh

output = exp4/NWE$(Cluster)_$(Process).out
error = exp4/NWE$(Cluster)_$(Process).err 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 1
request_memory = 20GB
request_disk = 2GB 

queue 30 n from params4.txt