container_image = docker://hyan84/centos7
universe = container

log = exp6/NWE$(Cluster).log
transfer_input_files = exp6.py, generator.py, utils.py, lowRank.py, params6.txt
arguments = $(n) $(delta_ratio) $(rate) 
executable = exp6.sh

output = exp6/NWE$(Cluster)_$(Process).out
error = exp6/NWE$(Cluster)_$(Process).err 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 1
request_memory = 20GB
request_disk = 2GB 

queue 1 n, delta_ratio, rate from params6.txt