container_image = docker://hyan84/centos7
universe = container

log = exp7/NWE$(Cluster).log
transfer_input_files = exp7.py, generator.py, utils.py, lowRank.py, params7.txt, sdp.py, glasso.py, mosek.lic
arguments = $(n) $(const) 
executable = exp7.sh

output = exp7/NWE$(Cluster)_$(Process).out
error = exp7/NWE$(Cluster)_$(Process).err 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 1
request_memory = 20GB
request_disk = 2GB 

queue 1 n, const from params7.txt